/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/apoderados` | `/apoderados`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/estudiantes` | `/estudiantes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/funcionarios` | `/funcionarios`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/proveedores` | `/proveedores`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/registrodiario` | `/registrodiario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/visitas` | `/visitas`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/apoderados` | `/apoderados`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/estudiantes` | `/estudiantes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/funcionarios` | `/funcionarios`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/proveedores` | `/proveedores`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/registrodiario` | `/registrodiario`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/visitas` | `/visitas`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/apoderados${`?${string}` | `#${string}` | ''}` | `/apoderados${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/estudiantes${`?${string}` | `#${string}` | ''}` | `/estudiantes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/funcionarios${`?${string}` | `#${string}` | ''}` | `/funcionarios${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/proveedores${`?${string}` | `#${string}` | ''}` | `/proveedores${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/registrodiario${`?${string}` | `#${string}` | ''}` | `/registrodiario${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/visitas${`?${string}` | `#${string}` | ''}` | `/visitas${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/apoderados` | `/apoderados`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/estudiantes` | `/estudiantes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/funcionarios` | `/funcionarios`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/proveedores` | `/proveedores`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/registrodiario` | `/registrodiario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/visitas` | `/visitas`; params?: Router.UnknownInputParams; };
    }
  }
}
